# Generated by Django 2.2.5 on 2021-09-01 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210901_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_verify',
            new_name='email_verified',
        ),
    ]
