# Generated by Django 2.2.5 on 2021-08-18 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20210818_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='hogst',
            new_name='host',
        ),
    ]
