# Generated by Django 2.2.5 on 2021-08-21 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20210821_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Accuracy',
            new_name='accuracy',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='Communication',
            new_name='communication',
        ),
    ]
